{{- if and .Values.ingress.api.enabled (eq .Values.ingress.controller "gatewayapi") }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}-api
  labels:
    app: {{ .Values.name }}-api
{{- with .Values.ingress.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- with .Values.ingress.api.domain }}
  hostnames:
    - {{ . | quote }}
{{- end }}
{{- with .Values.ingress.gatewayapi.gateways}}
  parentRefs: {{- . | toYaml | nindent 4 }}
{{- end }}
  rules:
{{- if .Values.ingress.dex.enabled }}
  - backendRefs:
    - kind: Service
      name: {{ .Release.Name }}-dex
      port: 5556
    matches:
    - path:
      type: PathPrefix
      values: {{ .Values.ingress.dex.path  }}
{{- end }}
  - backendRefs:
    - kind: Service
      name: {{ .Values.name }}-api-service
      port: 8080
    matches:
    - path:
      type: PathPrefix
      values: {{ .Values.ingress.api.path  }}
{{- end }}
