{{- if and .Values.ingress.api.enabled (eq .Values.ingress.controller "gatewayapi") }}
apiVersion: gateway.networking.k8s.io/{{ .Values.ingress.gatewayapi.apiVersion }}
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}-api
  labels:
    app: {{ .Values.name }}-api
{{- with .Values.ingress.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- with .Values.ingress.api.domain }}
  hostnames:
    - {{ . | quote }}
{{- end }}
{{- with .Values.ingress.gatewayapi.gateways}}
  parentRefs: {{- . | toYaml | nindent 4 }}
{{- end }}
  rules:
  - matches:
    - path:
        type: Exact
        value: "/.well-known/openid-configuration"
    backendRefs:
    - name: {{ .Values.name }}-api-service
      port: 8080
  - matches:
    - path:
        type: Exact
        value: "/.well-known/jwks"
    backendRefs:
    - name: {{ .Values.name }}-api-service
      port: 8080
{{- if .Values.ingress.dex.enabled }}
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.ingress.dex.path  }}
    backendRefs:
    - name: {{ .Release.Name }}-dex
      port: 5556
{{- end }}
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.ingress.api.path  }}
    backendRefs:
    - name: {{ .Values.name }}-api-service
      port: 8080

{{- end }}
