{{- if and .Values.ingress.registry.enabled (eq .Values.ingress.controller "gatewayapi") }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}-registry
  labels:
    app: {{ .Values.name }}-registry
{{- with .Values.ingress.registry.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- with .Values.ingress.registry.domain }}
  hostnames:
    - {{ . | quote }}
{{- end }}
{{- with .Values.ingress.gatewayapi.gateways}}
  parentRefs: {{- . | toYaml | nindent 4 }}
{{- end }}
  rules:
  - backendRefs:
    - kind: Service
      name: {{ .Values.name }}-registry-service
      port: 8075
    matches:
    - path:
      type: PathPrefix
      values: {{ .Values.ingress.registry.path  }}
{{- end }}
