{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-api-service
  labels:
    {{- include "terrakube-api.labels" . | nindent 4 }}
  {{- if or (and (eq .Values.ingress.controller "gke") .Values.ingress.gke.enabled .Values.ingress.gke.backendConfig.create) .Values.api.serviceAnnotations }}
  annotations:
    {{- if and (eq .Values.ingress.controller "gke") .Values.ingress.gke.enabled .Values.ingress.gke.backendConfig.create }}
    cloud.google.com/backend-config: '{"default": "{{ .Values.name }}-api-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
    {{- end }}
    {{- with .Values.api.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  # Use NodePort for GKE or the specified type from values (default to ClusterIP)
  type: {{ if eq .Values.ingress.controller "gke" }}NodePort{{ else }}{{ .Values.api.serviceType | default "ClusterIP" }}{{ end }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "terrakube-api.labels" . | nindent 4 }}
{{ end }}
